# Generated by Django 4.0.2 on 2022-12-17 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slig',
            new_name='slug',
        ),
    ]
