# Generated by Django 4.0.2 on 2023-03-24 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_ordered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordered',
            old_name='prodduct_name',
            new_name='product_name',
        ),
    ]
